name: SecOps Cloud Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  security-and-build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

    permissions:
      contents: read
      packages: write
      id-token: write  

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@2500896589ef8f7247069a56136f8dc177c27ccf  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN:  ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=zeroops-pfa
            -Dsonar.projectKey=zeroops_pfa_zeroops_test_app
            -Dsonar.host.url=https://sonarcloud.io

      - name: Run Trivy Security Scan
        uses: aquasecurity/trivy-action@6e7b7d1fd3e4fef0c5fa8cce1229c54b2c9bd0d8  
        with:
          scan-type: 'fs'
          format:    'table'
          severity:  'CRITICAL,HIGH'
          exit-code: '1'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567  
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75  
        with:
          context: .
          push: true
          tags: ghcr.io/zeroops-pfa/zeroops-test-app:sha-${{ github.sha }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
